env:
  browser: true
  es2021: true
extends:
  - "standard"
  - "prettier"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: { "no-console": "off", "@typescript-eslint/no-var-requires": "off" }
