exclude: ^web/static/vendored/.+$
default_language_version:
    node: lts
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=no]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.8.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@8.8.0
                - eslint-config-prettier@8.3.0
                - "@typescript-eslint/eslint-plugin@5.10.2"
                - "@typescript-eslint/parser@5.10.2"
                - "@angular-eslint/eslint-plugin@13.0.1"
                - "@angular-eslint/eslint-plugin-template@13.0.1"
                - "@angular-eslint/template-parser@13.0.1"
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
            exclude: ^(?!web\/frontend\/angular\/).+\.html$
    - repo: https://github.com/PyCQA/isort
      rev: 5.9.3
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear~=21.4
                - flake8-pytest-style~=1.5
                - pep8-naming~=0.11
