# Generated by Django 3.2.12 on 2022-03-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_parameter_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="priority",
        ),
    ]
