# Generated by Django 3.2.13 on 2022-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_test_add_django_q_schedule_3"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="testhistory",
            name="scheduled_timestamps_null",
        ),
        migrations.RemoveConstraint(
            model_name="testhistory",
            name="running_started_at_not_null_ended_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="testhistory",
            name="succeeded_timestamps_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="testhistory",
            name="cancelled_ended_at_not_null",
        ),
        migrations.AddConstraint(
            model_name="testhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "SC"), _negated=True),
                    models.Q(("ended_at__isnull", True), ("started_at__isnull", True)),
                    _connector="OR",
                ),
                name="scheduled_timestamps_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="testhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "RU"), _negated=True),
                    models.Q(("ended_at__isnull", True), ("started_at__isnull", False)),
                    _connector="OR",
                ),
                name="running_started_at_not_null_ended_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="testhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "SU"), _negated=True),
                    models.Q(("ended_at__isnull", False), ("started_at__isnull", False)),
                    _connector="OR",
                ),
                name="succeeded_timestamps_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="testhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "CA"), _negated=True),
                    ("ended_at__isnull", False),
                    _connector="OR",
                ),
                name="cancelled_ended_at_not_null",
            ),
        ),
    ]
